### ISSUE TITLE
Korean Translation Progress (v5)

### ISSUE THREAD

**Issue by alexkoala** [arumduri/bootstrap#1]
How to Contribute
----
1. 여기 이슈 댓글에 번역하길 원하는 페이지를 알려주세요. 중복 번역을 막기 위함입니다.
2. [번역 후 맞춤법에 문제가 없는지 확인한 후](https://speller.cs.pusan.ac.kr/), 풀 리퀘스트를 생성해주세요. (반대로 해도 상관없음)

Translation Guidelines
----
- 페이지 타이틀은 `title: 원문(번역)` 식으로 번역하며 Accessibility(접근성)과 같이 명확한 한글 단어가 존재하는 경우를 제외하고 음차를 원칙으로 함
- 페이지내 소타이틀은 원문 그대로
- `{{< callout >}}...{{< /callout >}}`은 번역하지 않음 (후순위)
- 고유명사 (예: Twitter, Bootstrap)는 번역하지 않음 ([Glossary](https://github.com/arumduri/bootstrap/wiki/Glossary) 참고)

Docs
----
- Getting started (@alexkoala)
    - [x] Introduction
    - [x] Download
    - [x] Contents
    - [x] Browsers & devices
    - [x] JavaScript
    - [x] Build tools
    - [x] Webpack
    - [x] Accessibility
    - [x] RFS
    - [x] RTL
    - [x] Parcel

- Customize (@jjulee)
    - [x] Overview
    - [x] Sass
    - [x] Options
    - [x] Color
    - [x] Components
    - [x] CSS variables
    - [x] Optimize

- Layout (@hwang1588 @alexkoala)
    - [x] Breakpoints
    - [x] Containers
    - [x] Grid
    - [x] Columns
    - [x] Gutters
    - [x] Utilities
    - [x] Z-index

- Content (@alexkoala)
    - [x] Reboot
    - [x] Typography
    - [x] Images
    - [x] Tables
    - [x] Figures

- Forms (@jjulee)
    - [x] Overview
    - [x] Form control
    - [x] Select
    - [x] Checks & radios
    - [x] Range
    - [x] Input group
    - [x] Floating labels
    - [x] Layout
    - [x] Validation

- Components (@jjulee)
    - [x] Accordion
    - [x] Alerts
    - [x] Badge
    - [x] Breadcrumb
    - [x] Buttons
    - [x] Button group
    - [x] Card
    - [x] Carousel
    - [x] Close button
    - [x] Collapse
    - [x] Dropdowns
    - [x] List group
    - [x] Modal
    - [x] Navs & tabs
    - [x] Navbar
    - [x] Offcanvas
    - [x] Pagination
    - [x] Popovers
    - [x] Progress
    - [x] Scrollspy
    - [x] Spinners
    - [x] Toasts
    - [x] Tooltips

- Helpers (@hwang1588)
    - [x] Clearfix
    - [x] Colored links
    - [x] Ratio
    - [x] Position
    - [x] Visually hidden
    - [x] Stretched link
    - [x] Text truncation

- Utilities (@hwang1588)
    - [x] API
    - [x] Background
    - [x] Borders
    - [x] Colors
    - [x] Display
    - [x] Flex
    - [x] Float
    - [x] Interactions
    - [x] Overflow
    - [x] Position
    - [x] Shadows
    - [x] Sizing
    - [x] Spacing
    - [x] Text
    - [x] Vertical align
    - [x] Visibility

- Extend (@alexkoala)
    - [x] Approach
    - [x] Icons

- About (@alexkoala)
    - [x] Overview
    - [x] Team
    - [x] Brand
    - [x] License
    - [x] Translations

- Migration (@jjulee)
    - [x] Migrating to v5

**Comment by hwang1588** [comment]
1. 작업예정 카테고리 (04-28 작성)
- Helpers
- Layout

2. 작업예정 카테고리 (04-29 작성)
- Utilities

**Comment by hwang1588** [comment]
Utilities 번역 우선 1차는 마무리 되었습니다. (5.0.1 기준으로)

**Comment by alexkoala** [comment]
@jjulee @hwang1588

곧 번역이 완료될 것으로 보이며 (현재 92.3%), 이후 다음과 같이 진행하려고 합니다.
1. 전체 번역 확인 후 오역 등 수정 (단일 PR로 진행할 예정)
2. 메뉴 번역
3. 이후 Maintenance Mode로 변경 (Permission revoke)
4. 푸터에 Translator Credit 추가 예정 (싫으신 분 있다면 알려주세요)

궁금하신 점이 있다면 알려주세요 ༼ つ ◕_◕ ༽つ

**Comment by alexkoala** [comment]
@hwang1588 남은 레이아웃 부분의 번역은 제가 해도 될까요?

**Comment by hwang1588** [comment]
> @hwang1588 남은 레이아웃 부분의 번역은 제가 해도 될까요?

제가 틈틈히 진행하고 있긴 한데 요즘 업무 때문에 속도가 안나오네요! 죄송하지만 부탁드리겠습니다!

**Comment by alexkoala** [comment]
번역 완료

**Comment by alexkoala** [comment]
@jjulee @hwang1588 모든 문서의 번역이 끝났습니다. 모두 수고하셨습니다!

**Comment by hwang1588** [comment]
@alexkoala @jjulee  정말 고생하셨습니다 :) 이제 디테일한 내용 및 문맥 문법 수정은 어떻게 진행 되나요?

**Comment by alexkoala** [comment]
> @alexkoala @jjulee 정말 고생하셨습니다 :) 이제 디테일한 내용 및 문맥 문법 수정은 어떻게 진행 되나요?

현재 v5.0.2로 올라가면서 번역이 되지 않은 부분 + 소제목을 번역하고 있고 기본적인 오타와 hugo 버그를 수정 중입니다. 완료되면 알려드리겠습니다.

**Comment by SpookyJelly** [comment]
안녕하세요. 좋은 번역 덕분에 편하게 부트스트랩 문서 읽을 수 있었습니다.
감사합니다. 

다른게 아니라 
Getting started -> Webpack/Parcel/Vite 세 페이지를 번역하고 싶은데, 가능할지 알고 싶어 이슈 남깁니다.

혹시 진행 중이실까요?

**Comment by alexkoala** [comment]
> 안녕하세요. 좋은 번역 덕분에 편하게 부트스트랩 문서 읽을 수 있었습니다.
> 감사합니다. 
> 
> 다른게 아니라 
> Getting started -> Webpack/Parcel/Vite 세 페이지를 번역하고 싶은데, 가능할지 알고 싶어 이슈 남깁니다.
> 
> 혹시 진행 중이실까요?

가능합니다! 다만 이 이슈는 이제 사용되지 않아서 따로 알리시지 않이도 Pull Request를 열어주시면 됩니다.
