### ISSUE TITLE
문서 단어 표기 방식 변경 건의

### ISSUE THREAD

**Issue by hwang1588** [arumduri/bootstrap#12]
한글 번역본 문서 전반에 'trigger' 라는 영어 표현이 한글 '트리거'로 표기 되고 있습니다.
'트리거'의 의미가 직관적이지 못해 이해하기 난해 하므로 표기 방식을 '발동' 으로 변경하려고 합니다.

의견 주시면 감사하겠습니다.

**Comment by alexkoala** [comment]
음... 저는 현행 유지가 낫다고 생각합니다.
@jjulee 님께서는 어떻게 생각하시나요?

**Comment by jjulee** [comment]
음.. 그렇군요..
'트리거'란 단어를 현장에서는 그대로 사용하고 있기에 '발동하다/발동되다' 라는 표현보다 더 이해하기 쉽지 않을까 생각했습니다.
의견 주신대로 '발동' 이란 표현으로 전체를 바꿔도 문제가 없을지는 각 페이지마다 확인이 필요할거 같습니다. 문맥상 부자연스러운 경우도 있을수 있을거 같아서요.

아 그리고 @hwang1588 님 덕분에 트리거 / 트리커가 혼재하고 있는 오타도 발견하게 되었습니다.
감사합니다.

@alexkoala @hwang1588 
확인 후 별도의 PR 로 연락 드리겠습니다.

**Comment by hwang1588** [comment]
trigger는 영어 발음대로 한글 '트리거'로 작성하겠습니다~! 의견 감사합니다 :)
