### ISSUE TITLE
부트스트랩5 정식버전이 발표 되었습니다.

### ISSUE THREAD

**Issue by hwang1588** [arumduri/bootstrap#13]
기쁘면서도 한편으로 생각이 많아지게 되었습니다.

05월06일 새벽4시를 기점으로 BS블로그에 부트스트랩5 정식 버전이 릴리즈 되었습니다.

(참고: https://blog.getbootstrap.com/)

현재 저희가 진행중인 한글화 작업은 BS5 BETA1을 기반으로 하고 있습니다.

 BS5 정식버전이 배포 되었기 때문에 한글화 문서도 정식버전으로 마이그레이션이 필요하다고 생각합니다.

의견 공유 부탁드립니다. 감사합니다.

**Comment by alexkoala** [comment]
5.0.0에 버그가 좀 있는 걸로 보여서 곧 5.0.1로 업데이트될 것 같습니다. 버전 업데이트는 그 후에 진행하려 하고 있습니다.

@hwang1588 @jjulee 
5.0.1이 나오면 현재 진행 중인 번역을 모두 merge하고 업데이트하려고 하는데, 동의하시나요?

**Comment by hwang1588** [comment]
네 동의합니다 @jjulee 님도 동의 하시면 금일까지 추가로 작업했던 번역본은 기존대로 Pr 드리겠습니다 :)

**Comment by hwang1588** [comment]
> 네 동의합니다 @jjulee 님도 동의 하시면 금일까지 추가로 작업했던 번역본은 기존대로 Pr 드리겠습니다 :)

우선 금일까지 작업했던 번역본은 PR 먼저 해놓겠습니다~!

**Comment by jjulee** [comment]
네 동의합니다.
번역중인 폼, 더 속도를 내겠습니다
