### ISSUE TITLE
v5.0.1 마이그레이션

### ISSUE THREAD

**Issue by hwang1588** [arumduri/bootstrap#18]
안녕하세요? 05-14(금) 기준 10시경에 v5.01로 한국어버전 마이그레이션을 확인 했습니다! (빠른 업데이트 감사드립니다!)

다름이 아니라 한글판을 v5.01로 마이그레이션 하면서 기존 번역 문서를 수정 하거나 추가해야 하는 부분이 있는 것으로

알고 있는데, 이부분은 어떤식으로 관리 되는 건가요?

**Comment by alexkoala** [comment]
안녕하세요, 5.0.1에서 추가적인 번역이 필요한 기존 파일은 다음과 같습니다.
사소한 변경은 업데이트하면서 수정했지만 많은 부분에서 추가적인 번역이 필요합니다.

@hwang1588 님 담당
site/content/docs/5.0/helpers/visually-hidden.md
site/content/docs/5.0/helpers/stretched-link.md
site/content/docs/5.0/utilities/api.md
site/content/docs/5.0/utilities/background.md
site/content/docs/5.0/utilities/borders.md
site/content/docs/5.0/utilities/colors.md
site/content/docs/5.0/utilities/display.md
site/content/docs/5.0/utilities/flex.md
site/content/docs/5.0/utilities/float.md
site/content/docs/5.0/utilities/interactions.md
site/content/docs/5.0/utilities/overflow.md
site/content/docs/5.0/utilities/position.md
site/content/docs/5.0/utilities/shadows.md
site/content/docs/5.0/utilities/sizing.md
site/content/docs/5.0/utilities/spacing.md

@jjulee 님 담당
site/content/docs/5.0/components/accordion.md
site/content/docs/5.0/components/alerts.md
site/content/docs/5.0/components/badge.md
site/content/docs/5.0/components/breadcrumb.md
site/content/docs/5.0/components/buttons.md
site/content/docs/5.0/components/card.md
site/content/docs/5.0/components/carousel.md
site/content/docs/5.0/components/close-button.md
site/content/docs/5.0/components/collapse.md
site/content/docs/5.0/components/dropdowns.md
site/content/docs/5.0/components/list-group.md
site/content/docs/5.0/components/modal.md
site/content/docs/5.0/components/navbar.md
site/content/docs/5.0/components/navs-tabs.md
site/content/docs/5.0/components/offcanvas.md
site/content/docs/5.0/components/pagination.md
site/content/docs/5.0/components/popovers.md
site/content/docs/5.0/components/progress.md
site/content/docs/5.0/components/scrollspy.md
site/content/docs/5.0/components/spinners.md
site/content/docs/5.0/components/toasts.md
site/content/docs/5.0/components/tooltips.md
site/content/docs/5.0/migration.md (내용 전체가 변경됨)
