### ISSUE TITLE
v5.0.2 Translation Review

### ISSUE THREAD

**Issue by alexkoala** [arumduri/bootstrap#36]
@jjulee @hwang1588 안녕하세요! 드디어 부트스트랩 5 번역이 끝났습니다. 소제목의 번역 등 #34 는 #35 에서 거의 완료했지만 제가 확인하지 못한 오역이나 자연스럽지 못한 번역, 미번역, 문법 오류 등이 남아있을 수 있습니다. 확인해주실 수 있나요?
참고로 문서 내 예시와 예시 페이지 자체는 제외하려고 하는데, 어떻게 생각하시나요?

**Comment by hwang1588** [comment]
@alexkoala  내 예시와 예시페이지는 제외 하는게 좋을 것 같습니다. 오역이나 미번역 같은 디테일한 사항은 어디서 확인하면 될까요?

**Comment by alexkoala** [comment]
> @alexkoala  내 예시와 예시페이지는 제외 하는게 좋을 것 같습니다. 오역이나 미번역 같은 디테일한 사항은 어디서 확인하면 될까요?

https://getbootstrap.kr/

**Comment by hwang1588** [comment]
@alexkoala 개선사항에 대한 내용은 어디에 올리면 될까요? 그냥 이곳에 코멘트 형식으로 전달 드리면 될까요?

**Comment by alexkoala** [comment]
넵

**Comment by alexkoala** [comment]
> @alexkoala 개선사항에 대한 내용은 어디에 올리면 될까요? 그냥 이곳에 코멘트 형식으로 전달 드리면 될까요?

넵

**Comment by alexkoala** [comment]
> 개선사항에 대한 내용은 어디에 올리면 될까요? 그냥 이곳에 코멘트 형식으로 전달 드리면 될까요?

넵
