### ISSUE TITLE
'보조': Secondary vs. Tertiary

### ISSUE THREAD

**Issue by kwon0408** [arumduri/bootstrap#65]
v5.3.0부터 추가된 tertiary 색상이 secondary와 똑같은 '보조'로 번역되고 있습니다.

예를 들면 [`new secondary and tertiary colors`](https://getbootstrap.com/docs/5.3/customize/color/#colors)는 [`새로운 보조 및 보조 색상`](https://github.com/arumduri/bootstrap/blob/354837fcd0af9033bddf4a9d06e49c0a25850dc4/site/content/docs/5.3/customize/color.md)으로 표현되어 있습니다.

**Comment by alexkoala** [comment]
@kwon0408 [단어를 그대로 두는 식으로 번역을 변경했는데](https://deploy-preview-66--gracious-pare-4b0ef5.netlify.app/docs/5.3/customize/color/#색상), 어떠실까요?

**Comment by kwon0408** [comment]
'secondary → 보조'는 그대로 두고 'tertiary → 참고' 정도로 하면 될 것 같네요.
