### ISSUE TITLE
can't upload file arumduri / bootstrap  new branch 

### ISSUE THREAD

**Issue by hwang1588** [arumduri/bootstrap#8]
hello~! i want contribute korean bootstrap. how can i uplaod here and pr your main branch(repo)?

**Comment by alexkoala** [comment]
안녕하세요,

이 저장소의 `main` branch를 fork하고
#1 을 확인하신 다음에 `main/site/content/docs/5.0` 경로 아래에 있는 문서 파일을 수정하시면 됩니다 :)

**Comment by hwang1588** [comment]
감사합니다 오늘 한번 해보겠습니다~!

**Comment by hwang1588** [comment]
기존 번역본들 중에 문법이나 번역상 어색한 부분을 업데이트 하고 싶은데 혹시 기존 Contributor들의 번역본을 추가로 수정하면 실례가 될까요~?

**Comment by alexkoala** [comment]
상관없습니다!
